spring:
  datasource:
    url: jdbc:postgresql://82.202.138.26:5430/hostelService

rabbitmq:
  notification-service:
    addresses: 82.202.138.26:5672

otlp:
  tracing:
    endpoint: http://10.43.140.102:4317