apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: userservice
          image: ghcr.io/tpabka251/userservice:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "0Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health  # эндпоинт health для проверки состояния
              port: 8080
            initialDelaySeconds: 300    # Задержка перед первым запросом
            periodSeconds: 60          # Интервал проверки
            timeoutSeconds: 30          # Время ожидания ответа
            failureThreshold: 3        # Количество неудачных попыток до перезапуска

          readinessProbe:
            httpGet:
              path: /actuator/health  # тот же эндпоинт для проверки готовности
              port: 8080
            initialDelaySeconds: 120    # Задержка перед первым запросом
            periodSeconds: 20          # Интервал проверки
            timeoutSeconds: 30         # Время ожидания ответа
            failureThreshold: 3
